[package]
name = "jilu"
version = "0.1.0"
authors = ["Jean Mertz <helloworld@rustic.games>"]
license = "MIT OR Apache-2.0"
description = "Generate a change log based on conventional commits."
repository = "https://github.com/rustic-games/jilu"
keywords = ["changelog", "git", "conventional commits", "change log"]
categories = ["command-line-utilities", "development-tools", "template-engine"]
readme = "README.md"
edition = "2018"

[dependencies]
Inflector = { version = "0.11", default-features = false }
chrono = { version = "0.4", default-features = false }
conventional-commit = "0.1"
git2 = { version = "0.9", default-features = false }
lazy_static = "1.3"
pulldown-cmark = { version = "0.5", default-features = false }
semver = "0.9"
